import Link from "next/link";
import {
  ArrowUpRight,
  Check,
  CloudDrizzle,
  Eye,
  MapPin,
  Users,
  X,
  Zap,
} from "lucide-react";
import StatCard from "@/components/stat-card";
import TrafficLight from "@/components/traffic-light";
import {
  mockContextSignals,
  mockKPIs,
  mockOfferActivity,
} from "@/lib/mock-data";
import { cn } from "@/lib/utils";

const statusBadge = {
  accepted: {
    icon: Check,
    className: "bg-emerald-50 text-emerald-700 border-emerald-200",
    label: "Accepted",
  },
  shown: {
    icon: Eye,
    className: "bg-ink-100 text-ink-600 border-ink-200",
    label: "Shown",
  },
  dismissed: {
    icon: X,
    className: "bg-rose-50 text-rose-600 border-rose-200",
    label: "Dismissed",
  },
} as const;

const signalIcon = {
  Weather: CloudDrizzle,
  "Foot traffic": Users,
  "Local event": MapPin,
  "Payone density": Zap,
} as const;

export default function OverviewPage() {
  return (
    <div className="max-w-7xl mx-auto space-y-8">
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Today</h1>
          <p className="text-sm text-ink-500 mt-1">
            Tuesday, 21 April · Live demand and offer performance.
          </p>
        </div>
        <Link
          href="/monitoring"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-brand-600 hover:text-brand-700"
        >
          Open monitoring
          <ArrowUpRight className="size-4" />
        </Link>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {mockKPIs.map((kpi) => (
          <StatCard key={kpi.label} {...kpi} />
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 rounded-2xl border border-ink-200 bg-white p-6">
          <div className="flex items-center justify-between mb-5">
            <div>
              <h2 className="font-semibold">Live offer activity</h2>
              <p className="text-xs text-ink-500 mt-0.5">
                Generated by City Wallet AI in the last hour.
              </p>
            </div>
            <div className="flex items-center gap-1.5 text-xs text-ink-500">
              <span className="size-1.5 rounded-full bg-emerald-500 animate-pulse" />
              Auto-refreshing
            </div>
          </div>

          <div className="space-y-2">
            {mockOfferActivity.map((o) => {
              const meta = statusBadge[o.status];
              const Icon = meta.icon;
              return (
                <div
                  key={o.id}
                  className="flex items-center justify-between gap-4 p-3 rounded-xl border border-ink-100 hover:border-ink-200 transition"
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <span
                      className={cn(
                        "size-8 rounded-lg border grid place-items-center shrink-0",
                        meta.className
                      )}
                    >
                      <Icon className="size-4" />
                    </span>
                    <div className="min-w-0">
                      <div className="text-sm font-medium truncate">
                        {o.offer}
                      </div>
                      <div className="text-xs text-ink-500 truncate">
                        {o.context}
                      </div>
                    </div>
                  </div>
                  <div className="text-xs text-ink-400 shrink-0">{o.time}</div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="space-y-6">
          <TrafficLight compact initial="bring-them-in" />

          <div className="rounded-2xl border border-ink-200 bg-white p-5">
            <div className="text-xs uppercase tracking-wider text-ink-500 mb-3">
              Live context signals
            </div>
            <div className="space-y-3">
              {mockContextSignals.map((s) => {
                const Icon =
                  signalIcon[s.label as keyof typeof signalIcon] ?? Zap;
                return (
                  <div
                    key={s.label}
                    className="flex items-center gap-3"
                  >
                    <span className="size-8 rounded-lg bg-ink-100 grid place-items-center shrink-0">
                      <Icon className="size-4 text-ink-600" />
                    </span>
                    <div className="flex-1 min-w-0">
                      <div className="text-xs text-ink-500">{s.label}</div>
                      <div className="text-sm font-medium truncate">
                        {s.value}
                      </div>
                    </div>
                    <div className="text-[11px] text-ink-400 shrink-0">
                      {s.detail}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
